// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"database/sql"
)

type OauthState struct {
	ID          int64          `json:"id"`
	State       string         `json:"state"`
	RedirectUrl string         `json:"redirectUrl"`
	ExpiresAt   string         `json:"expiresAt"`
	CreateAt    sql.NullString `json:"createAt"`
}

type Post struct {
	ID       int64          `json:"id"`
	UserID   int64          `json:"userId"`
	Title    string         `json:"title"`
	Content  sql.NullString `json:"content"`
	UpdateAt sql.NullString `json:"updateAt"`
	CreateAt sql.NullString `json:"createAt"`
}

type Token struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"userId"`
	RefreshToken string         `json:"refreshToken"`
	ExpiresIn    int64          `json:"expiresIn"`
	CreateAt     sql.NullString `json:"createAt"`
}

type User struct {
	ID         int64          `json:"id"`
	Email      string         `json:"email" validate:"required,email"`
	Password   sql.NullString `json:"password" validate:"required,min=8,max=32"`
	Name       string         `json:"name"`
	Bio        sql.NullString `json:"bio"`
	Provider   sql.NullString `json:"provider"`
	ProviderID sql.NullString `json:"providerId"`
	IsAdmin    int64          `json:"isAdmin"`
	UpdateAt   sql.NullString `json:"updateAt"`
	CreateAt   sql.NullString `json:"createAt"`
}
